#!/usr/bin/node
//

const filepath = process.argv[2];
const fs = require('fs');


fs.readFile(filepath, 'utf-8', (error, data) => {
  if (error) {
	  console.log('error');
  }
  console.log(data);
});
